language: ruby
cache: bundler
rvm:
- 2.5
before_install:
- gem update --system
- gem install bundler
- bundle install
- bundle lock --remove-platform x86-mingw32
- bundle exec danger
stages:
- default
jobs:
  include:
    stage: default
    name: Main Application
deploy:
  provider: heroku
  app: infinite-caverns-26154
  skip_cleanup: true
  api_key:
    secure: DtsYkuTrTUOig7xOAiIUoV6TJyKZFSMS1pz+H4x9irno1uIDokv9chle7bUX86fnF3hpxw4E7b4UG+c9PncPMXZV9tT0dBtydeL66uS6Lx2T5XKUesXtvZ7IdZ9kKLdSklfzG2nh+CClMONDcrhZh3nFtFysFbaG3ngKYW6XbmM+BhsYYWFZSb/25Rh3vvN317klogzlm8abcV7HYOcaNdQhpkfig0cyOM0aZRuodfwVtOIDubYGIXtV+vHARvK69AGrf53kodVxMxTV4aC2ZDxFFHD282SfTfQ123RNNpt9SHJatFC5WB7aOMpSPSDcVnBGdrNXPZvpqpMoZ01CTd63g99NlHzht9Y2Y6BZUNVI+ASYK/GxlK2iPqEsnbhBjIZ0Q8G6fG3JnTJ1cdQSJSs4MCvr8VLr5gTZj9AeCd3jnnkeM5HKuyCHRtYfRmYy0467ud7osJV19W83orUuvcGWqDYqCnl7KaTaHo81mQ16zvn324hu+fhPDoayK338rPvKQ1XktA1fxm2PeeRe6MvC+/ywreit1IdmtE3aLf6lLC16kDiSm7whej94rV+UhssuvDtWJjsvHeBycWP2wAeIxYuKuFk0R15JyaNWmmUdyl0eFO1x2sXrBrI3bFOEMtf4j79FyCogkc8fRssmRa7Nszp0TC5i6BdmPRHQs9g=
