language: ruby
cache: bundler
rvm:
- 2.5
before_install:
- gem update --system
- gem install bundler
- bundle lock --remove-platform x86-mingw32
- bundle exec danger
stages:
- default
jobs:
  include:
    stage: default
    name: Main Application
deploy:
  provider: heroku
  app: infinite-caverns-26154
  skip_cleanup: true
  api_key:
    secure: OmYZGHnBCgyqoqkbej83So5ONTRf5Msjw/Soi0ofZK5MkPpitcGfIJTH5CHNAfQ57WYTFT9wOQBOQDVtHjoEEkhEW23siP4uPkzCRcENfjBuFEVibjjjx4bZ1dEN4w2Z5fj9SqioBblT8J7QOBcwFrN83e11ticI1x15a0i8Nem5FhSilwgvsU5rePDDnhGhvjLQHigonKRP444D9iHsfBZHc5izOLMZt4ecyw+Ehux6az3HAP1IrlVU6YFGbgWGCN07snsA3/uYeH7AHm3X+nOff336hEc7fmi62SOfR5pxvNbcvVO8ybmgE1CQ4lFgJSPoWJ5Rb2AWqpX2Vs/FuOAQzURdOGSEzyj8Sg9eHbEDaYrdEi/fhUIDV2y5uyeRM5dU6Bp3UA6icMhPOfudQNH7wmTGHaxVrQhRVm5rk248uXCW8y17owAg2lGID3okKftycWzFbjlHN2yqzLBwPBCefRfnAaoMCaKeTIGP1rqjWzdpWk+OM733QBlX5A8ij6OWCeHPf+qv7Tv5uusQWscuPYX0iK98otoylPF4WawLU/Mh5HLfEd5VEvcMUc8eIwoLjMfrX3ukCJFPiH2b9316T5BMel4N4Qo8Q3xD3Q46tQ6ftFMe7M5FDsLoIZO8yG5iLmJg2ZRegtBDkT21PCaal9rqMi65yR8H6M2PofQ=
