language: ruby
cache: bundler
rvm:
- 2.5
before_install:
- gem update --system
- gem install bundler
stages:
- default
jobs:
  include:
    stage: default
    name: Main Application
deploy:
  provider: heroku
  api_key:
    secure: eSvM56hv+DstB9mPXW3yPBJh1s0kF16IFZRZRXFxiVbuImxa8jYpicXbHhq5YS4PtHRidSbRvigHcApc/wi3dd9LLV6C9+81qfEECHTJyRRQUz8HbA3ogQeNn2lSTTU9x77zaTUHW2vE2HOCWeEovb6nJxiHywrie+h7XHIns1jp2J5pyTGUraPHpq7iX3U5+SiS3sz3uOorO8M5RwjRsuiWosHI8idPEu6NfLpbQgq77DjPiB00N5oZaT7iSZj2vh+sZ4IYPgUsEHDYZwLRIWeF8YPJzFKyP35+VfeM1j319EHF5bwdRVzX58jMywtlipe65HavB48WdsJHQ3b3V7hHVF+q+mzeLWskSO6eH34sIbFXvMaFPxjttsSiXW2pXwDwCBGmnHsITDKokURJ0Cysx7MQPQBNbbyHqp4ypiMJflDhHYLuHE1N+KYou/WvGujFQXES0oyTPZLJ6dUCJ0Xv7d6pzXS0GevmWqd2FNUB2KSDHCcymXOJpZo+0cPMfsXzzE8cr2KqubWc+9S3/y3Y1G3Dnc4EXPx8NGZrtxUkKbbV4EKuX+U3uEaXXNgjuGDKyqioPufm8ZhM4PXY/NHHF2qpeUozWuyAE6UqgWVZidOPPO1VVYnldU9AKV8nsO6U2J8LQ5fIzFURqFLT133rtom30N+WhXyDsizQDJw=
