language: ruby
cache: bundler
rvm:
- 2.5
before_install:
- gem update --system
- gem install bundler
- bundle install
- bundle lock --remove-platform x86-mingw32
- bundle exec danger
stages:
- default
jobs:
  include:
    stage: default
    name: Main Application
deploy:
  provider: heroku
  app: infinite-caverns-26154
  skip_cleanup: true
  api_key:
    secure: NIf9rsR0i8FdCuvDSe70UmjPfCzj4tGTtmryhU2lYJwS2+dnnHwB63oyk+90RMMsgea3zDgpm2QqlQiGZ54nvr5NENVDKwQbXVBaEci6GHw3JcOarYtBb7UzieTXRupATKMl0d+Jw3eKfLAN5ez0cBRsG/d6A1BY/YE6RxhD73+yxs6WBBwz49agz3VpS6INDUo3xNEfDh/yCj8kmPuD7RoO04Gzwj/GEwEUqhvQC6Fwx+IWFKO7zQd0GA4kxN8pPVXU5pAXVICPfUhPfxKrmNTzB5f8+RMcinQ1QACIPbLgXExwZUAKQAc4AgCWPX+IxanbLdQsr1NQDAFn2gpf6CvzwRpT2Vd+mfeMZilaO53Mc+ByP3tbnuX4cLQD00HXZD6J19QcnL9w2IEQA0tLtFD32gnY2/Ct+2+nO6TqEwdDDKHJZeJj5I9iInHPSw3gxjBeqAAHFi/0d0aS5Y+6i+vzK/5eorNqw0l+z4DkVY59TWHaJmZY6J9lHJKIipJ3dHpSoMlRn8ytjdmwh8NIk2yRfugCEK7vk2jKXJie2dQxtTj5MhgjRW67hDjkjcbrXelTD6K+xZk6IAutGKrjr56krg4bf+jNz2e5ndPPe1WWBPtOzvVv67D/bxP8gRxSOLlMJQ1HEjmxt7itippTUvNmB4Mea3cony6J5dS6taA=
